### ISSUE TITLE
Writing makes database files exceedingly big

### ISSUE THREAD

**Issue by inetic** [equalitie/ouisync#106]
On commit dfbcf6ad

To reproduce:

* Have two write replicas `A` and `B` sharing a common repository
* Copy a 30MB big file to replica `A`
* Let `B` sync with `A`

A's database files are ~248MB big (~123MB in the `.db` file and ~125MB in the `.db-wal` file). B's database files are only ~55MB big.

**Comment by inetic** [comment]
Yes, but 123MB for the `.db` also seems big given that once all the data is copied to `B` the database on `B` only takes up 55MB. It seems as if `A` is not deleting some data (e.g. outdated branches or modified/removed blocks) while it's writing to the file.

**Comment by madadam** [comment]
The WAL is likely not the full story but still worth looking into.

**Comment by madadam** [comment]
Also, 55MB of db size for 30MB of actual data still seems like quite a lot of overhead.

**Comment by madadam** [comment]
Running [`VACUUM`](https://www.sqlite.org/lang_vacuum.html) reduces the db size to one with very little overhead (31 - 32 MB for a 30MB of the actual data)

**Comment by madadam** [comment]
Experimenting with different [page_sizes](https://www.sqlite.org/pragma.html#pragma_page_size) made no difference (actually higher page sizes made the overhead worse). Enabling [auto_vacuum](https://www.sqlite.org/pragma.html#pragma_auto_vacuum) does not seem to have any effect either (which is somehow surprising) .

**Comment by madadam** [comment]
I tried to upload a 500MB file into an empty repo and running VACUUM afterwards, the db size was ~17MB higher than the file which doesn't seem to be too bad for now. However the pre-vacuum overhead is a concern and we should find a way to deal with it. Perhaps run VACUUM automatically at some appropriate moments?

**Comment by madadam** [comment]
Instead of uploading a single 30MB file, I tried uploading 30 1MB files and the overhead (without VACUUM) was much lower - 37MB for db and 12MB for wal. Hypothesis: the high overhead might be possibly caused by the whole file being written in a single transaction. Maybe periodically committing it every once in a while could fix this? The transaction batching was implemented as a optimization because it improved write speed quite dramatically, but seems it's a tradeoff between speed and db size.

**Comment by madadam** [comment]
Turns out the excessive size was caused by us not removing old snapshot immediately after a new one is created but only in the worker during garbage collection. Because the worker is notified only when the file is flushed, uploading a large file caused large number of snapshots (equal to the number of blocks in the file) to be created and held in the db until the file was flushed. This for some reason caused the db to become excessively big - much bigger than the size of the actual data stored in it (blocks + index).
